version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27025:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-node-ts
    command: npm start
    volumes:
      - ./dist:/usr/app/dist
    environment:
      MONGO_URL: mongodb://mongo:27017/clean-node-ts
    ports: 
      - "5050:5050"
    links:
      - mongo